# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ppd3rn84e5LAiN_tukZDJ8VWrT9og5vx
"""



"""Conhecendo Base de Dados"""

import pandas as pd

url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
pd.read_csv(url)

pd.read_csv(url, sep=';')

dados = pd.read_csv(url, sep=';')
dados

dados.head()

dados.tail()

type(dados)

dados.shape

dados.columns

dados.info()

dados['Tipo']

dados[['Quartos', 'Valor']]

dados.head()

dados['Valor'].mean()

dados.groupby('Tipo').mean(numeric_only=True)

dados.groupby('Tipo')['Valor'].mean(numeric_only=True)

dados.groupby('Tipo')[['Valor']].mean(numeric_only=True).sort_values('Valor')

df_preco_tipo = dados.groupby('Tipo').mean()[['Valor']].sort_values('Valor')

df_preco_tipo.plot(kind='barh', figsize=(15, 10), color ='blue');



"""**Removendo os imóveis comerciais**"""

dados.Tipo.unique()

imoveis_comerciais = ['Conjunto Comercial/Sala',
                      'Prédio Inteiro', 'Loja/Salão',
                      'Galpão/Depósito/Armazém',
                      'Casa Comercial', 'Terreno Padrão',
                      'Loja Shopping/ Ct Comercial',
                      'Box/Garagem', 'Chácara',
                      'Loteamento/Condomínio', 'Sítio',
                      'Pousada/Chalé', 'Hotel', 'Indústria']

dados.query('@imoveis_comerciais in Tipo')

dados.query('@imoveis_comerciais not in Tipo')

df = dados.query('@imoveis_comerciais not in Tipo')
df.head()

df.Tipo.unique()

df = dados.groupby('Tipo').mean()[['Valor']].sort_values('Valor')

df_preco_tipo.plot(kind='barh', figsize=(15, 10), color ='blue');

df.Tipo.value_counts(normalize=True).to_frame().sort_values('Tipos')

df_percentual_tipo = df.Tipo.value_counts(normalize=True).to_frame().sort_values('Tipos')